### ISSUE TITLE
Blue background not working when in git repo

### ISSUE THREAD

**Issue by shern91** [AmrEldib/cmder-powerline-prompt#15] opened 2017-04-20 03:52 UTC
Hi, I followed all those step to setup my cmder, it work fine when I in normal directory. But when I "cd" into my git repo, the blue background is not working, back to normal view. (The only step I didn't follow was copy all the init.bat you provided replace to my current init.bat, I just copy certain code didn't exist in my current init.bat and add into it, If I replace your init.bat to my init.bat, i get this error.)

![untitled](https://cloud.githubusercontent.com/assets/16183843/25213200/854db21e-25c1-11e7-922b-91e47a7ff8f7.png)

OS:              Windows 10 64 bit
Git Version: 2.12.0

![screenshot](https://cloud.githubusercontent.com/assets/16183843/25212821/6120998a-25bf-11e7-96d9-46c69cf5850b.png)

**Comment by novakin** [comment] 2017-06-07 05:23
same issue

**Comment by AmrEldib** [comment] 2017-06-07 06:06
Some users ran into issues with character encoding, I've clarified the settings for it in the [Font section](https://github.com/AmrEldib/cmder-powerline-prompt#font). Please make sure to apply those changes.  
@shern91 you've mentioned changes to the `init.bat` file, but this prompt doesn't require changes to this file. You just need to place the `.lua` file in the `%CMDER_ROOT%/config` folder. What changes did you make?

**Comment by novakin** [comment] 2017-06-07 06:08
I have the same issue as @shern91, with cmd, in a git repo, it fallsback to the default display.

I have placed the lua file in the %CMDER_ROOT%/config, I have modified the settings as stated in the readme

**Comment by AmrEldib** [comment] 2017-06-07 06:15
@novakin what version of Cmder and Git? do you get the result in the [second screenshot](https://cloud.githubusercontent.com/assets/16183843/25212821/6120998a-25bf-11e7-96d9-46c69cf5850b.png)?

**Comment by novakin** [comment] 2017-06-07 07:10
@AmrEldib Yes I do get the result of the second screen.

I have the latest version of CMDER, latest stable version of ConEmu (also tested with latest alpha) and latest of GIT (2.13.0.windows.1)

**Comment by AmrEldib** [comment] 2017-06-21 05:33
Hi @shern91 @novakin I've tested with the latest version of git, but I"m not able to reproduce this problem :(
I'll close this, but if you can provide more details to help narrow down the cause of the problem, I'm happy to help.

**Closed as completed by AmrEldib** 2017-06-21 05:33 UTC

**Comment by shern91** [comment] 2017-06-30 04:51
Hi @AmrEldib I solve the background problem with reinstall the cmder. But now the only problem i faced is cmder can't get yellow background for changes, will always show green background no matter the repo is clean or changes.

![cmder](https://user-images.githubusercontent.com/16183843/27721443-df73f506-5d92-11e7-9f2f-0efb171aa63b.png)
